name: Nmap Script CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run syntax check
        run: bash -n script.sh

      - name: Execute Nmap Script
        run: ./script.sh 
